language: node_js

sudo: false

cache:
  directories:
    - node_modules

node_js:
  - 10
  - 12

install: npm install

script:
  - npm run lint
  - npm run test

notifications:
  email:
    on_success: never
    on_failure: change
